### ISSUE TITLE
Error in opening the Statistics PDFs

### ISSUE THREAD

**Issue by Hazzerback25** [krishnaik06/The-Grand-Complete-Data-Science-Materials#116]
In the 'Complete Statistics' folder, the files named "stat1.pdf","stat2.pdf","stat3.pdf","stat5.pdf" show an error saying 'Invalid PDF' thereby making them inaccessible.
Probably requires a re-upload.
<img width="890" alt="Screenshot 2023-12-26 at 1 32 47 AM" src="https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials/assets/85587494/5897c12e-b994-407a-ac43-d0d682c231f1">

**Comment by sumit-jr** [comment]
we can download and see the file. It's opening after downloading.
![Uploading Screenshot 2023-12-26 at 09.21.21.png…]()

**Comment by praj2408** [comment]
Disable IDM extension in your chrome extension. hope it works!
