### ISSUE TITLE
Cannot access / download any pdf 

### ISSUE THREAD

**Issue by VGMM** [krishnaik06/The-Grand-Complete-Data-Science-Materials#128]
This is the error ,I see whenever I click on any pdf
![image](https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials/assets/153889298/b8c476c6-1614-4a8f-aba4-12e06d136a27)

**Comment by praj2408** [comment]
Disable your IDM extension in chrome and try

**Comment by krishanwalia30** [comment]
Is the issue still there, because I don't see any problem as stated.

![image](https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials/assets/101003187/39bacbd2-8088-43be-9ff4-06a0474234c7)

**Comment by VGMM** [comment]
The issue is resolved thank you

**Comment by praj2408** [comment]
how did you solve it?

**Comment by VGMM** [comment]
> how did you solve it?

I din't ,I can just access the files now while opening it ,Try opening it now
