### ISSUE TITLE
Unable to Download Data-Science-Materials File

### ISSUE THREAD

**Issue by baijukb** [krishnaik06/The-Grand-Complete-Data-Science-Materials#2]
Hello Krishna,

I'm encountering an issue when attempting to download the below mentioned file from your repository. I've followed the usual steps for downloading this file, but it doesn't seem to be working as expected.

https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials/blob/main/Complete%20MySQL%20Interview%20Materials/Complete%20SQL%20Basics%20To%20Advance%20Guide.pdf

Please look into it. 

Thanks
Baiju

**Comment by mr-zulme** [comment]
Same For me I m Also not able to download any of files

**Comment by KrsnaAleti** [comment]
Its working fine for me
![image](https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials/assets/118866851/46cf78ba-602f-4b12-8bd7-9718c7c82cfd)

**Comment by jamesalvin49** [comment]
#### To download the specific file you're referencing, you can try different method(s):

+ ### Clone the entire repository:
    + Open your command prompt or terminal on your computer.
    + You can just navigate to the directory where you'd like to save the repository.
    + Run the following command:
`git clone https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials.git`
    + Once the repository is cloned, you can access the desired file locally.
+ ### Download from GitHub directly:
    + Navigate to the main page of the repository or use this link.
    + Click on the 'Code' button (green button) and select 'Download ZIP'.
    + Once downloaded and extracted, you should be able to navigate to the specific folder and access the file.
+ ### Downloading a Specific File from GitHub:
    + Open the repository on GitHub.
    + Browse to the file you want to download.
    + Click on the filename to open it.
    + On the top right of the file viewer, you'll see a Download Raw button. Click on it. This will download the raw version of the file to your computer.


If you're still encountering issues, please let me know the specific error message or issue you're facing, and I'll be happy to assist further.

**Comment by maityshreya** [comment]
Same for me no files get downloaded.

**Comment by baijukb** [comment]
I have tried the second option, "Download from GitHub directly:" and it worked. Thanks.
