### ISSUE TITLE
Not Visible "Walmart-SalesBot-and-SearchGPT project"

### ISSUE THREAD

**Issue by Shaon2221** [krishnaik06/The-Grand-Complete-Data-Science-Materials#81]
Hi Krish,
I have added Walmart Salesbot and SearchGPT project in ML Project repository and you have merged with your own repo. But it seems it doesn't work. Don't know what happened. If I click on the project it redirect to an error page. 
[Walmart-SalesBot-and-SearchGPT project](https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials/blob/main/ML%20Projects/Walmart-SalesBot-and-SearchGPT)
![image](https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials/assets/18596945/e0a692f2-156d-48f7-94e0-273102791368)
![image](https://github.com/krishnaik06/The-Grand-Complete-Data-Science-Materials/assets/18596945/98daaf63-cea9-43dd-9d62-bbcd59331e05)

Kindly check at your convenient time and let me know if I have to do anything else from my end.

Thank you Krish for your time and this great initiative.

**Comment by Rajarshi12321** [comment]
Hi @Shaon2221 I was just going through the repository and came across your issue. I had this same issue when I submitted my repository, in my case the project folder contained a .git folder inside it, and when I pushed it into the repository it resulted in git recognizing it as a submodule.  
You may check if you have a hidden .git file in your uploaded folder, if present then remove it and try to upload again.

**Comment by Shaon2221** [comment]
Thanks brother. Didn't knew this. Let me try this.
